global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'spring-boot-monitor'

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:7010']
        labels:
          application: 'your-app-name'
          environment: 'dev'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
